package solutions;

import lib.AbstractSolution;
import lib.PEUtils;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Solution002 extends AbstractSolution {

    @Override
    public String run() {
        return PEUtils.getFibonacciMax(4000000).stream()
                .filter(fib -> fib % 2 == 0)
                .reduce(0L, (a, b) -> (a + b)).toString();
    }
}
